version: "2"

run:
  go: '1.24'

linters:
  exclusions:
    rules:
      - linters:
          - forbidigo
        path: internal/syncutil/
  enable:
    - staticcheck
    - errcheck
    - gosec
    - govet
    - unused
    - ineffassign
    - sqlclosecheck
    - rowserrcheck
    - revive
    - gocritic
    - nolintlint
    - gocyclo
    - funlen
    - bodyclose
    - nilerr
    - unconvert
    - usestdlibvars
    - errorlint
    - exhaustive
    - prealloc
    - noctx
    - nilnil
    - errname
    - wrapcheck
    - gocognit
    - cyclop
    - nestif
    - maintidx
    - makezero
    - sloglint
    - gosmopolitan
    - tagliatelle
    - testableexamples
    - testifylint
    - varnamelen
    - decorder
    - dupl
    - goheader
    - grouper
    - paralleltest
    - tparallel
    - copyloopvar
    - intrange
    - nakedret
    - forbidigo
  settings:
    govet:
      enable:
        - shadow
        - fieldalignment
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
    gocyclo:
      min-complexity: 15
    funlen:
      lines: 80
      statements: 50
    prealloc:
      simple: true
      range-loops: true
      for-loops: true
    revive:
      severity: warning
      rules:
        - name: argument-limit
          arguments: [5]
        - name: atomic
        - name: bool-literal-in-expr
        - name: call-to-gc
        - name: cognitive-complexity
          arguments: [15]
        - name: comment-spacings
        - name: confusing-naming
        - name: confusing-results
        - name: constant-logical-expr
        - name: context-as-argument
        - name: context-keys-type
        - name: cyclomatic
          arguments: [15]
        - name: datarace
        - name: deep-exit
        - name: defer
        - name: dot-imports
        - name: duplicated-imports
        - name: early-return
        - name: empty-block
        - name: empty-lines
        - name: error-naming
        - name: error-return
        - name: error-strings
        - name: errorf
        - name: flag-parameter
        - name: function-length
          arguments: [50, 0]
        - name: function-result-limit
          arguments: [3]
        - name: get-return
        - name: identical-branches
        - name: if-return
        - name: import-alias-naming
        - name: import-shadowing
        - name: increment-decrement
        - name: indent-error-flow
        - name: line-length-limit
          arguments: [120]
        - name: max-control-nesting
          arguments: [3]
        - name: modifies-parameter
        - name: modifies-value-receiver
        - name: nested-structs
        - name: optimize-operands-order
        - name: range-val-address
        - name: range-val-in-closure
        - name: range
        - name: receiver-naming
        - name: redefines-builtin-id
        - name: redundant-build-tag
        - name: redundant-import-alias
        - name: redundant-test-main-exit
        - name: string-of-int
        - name: struct-tag
          arguments: ["toml,multiline"]
        - name: superfluous-else
        - name: time-date
        - name: time-equal
        - name: time-naming
        - name: unchecked-type-assertion
        - name: unconditional-recursion
        - name: unexported-naming
        - name: unexported-return
        - name: unhandled-error
        - name: unnecessary-format
        - name: unnecessary-stmt
        - name: unreachable-code
        - name: unused-parameter
        - name: unused-receiver
        - name: use-any
        - name: use-errors-new
        - name: use-fmt-print
        - name: useless-break
        - name: var-declaration
        - name: var-naming
        - name: waitgroup-by-value
    gocognit:
      min-complexity: 15
    cyclop:
      max-complexity: 15
    nestif:
      min-complexity: 4
    varnamelen:
      min-name-length: 2
      ignore-names: ["err", "id", "i", "j", "k", "db", "tx", "ctx", "wg"]
    tagliatelle:
      case:
        rules:
          json: snake
    dupl:
      threshold: 100
    wrapcheck:
      extra-ignore-sigs:
        - .Err(
    forbidigo:
      forbid:
        - pattern: 'sync\.Mutex'
          msg: "use syncutil.Mutex instead of sync.Mutex for deadlock detection support"
        - pattern: 'sync\.RWMutex'
          msg: "use syncutil.RWMutex instead of sync.RWMutex for deadlock detection support"
      exclude-godoc-examples: true
      analyze-types: true
    goheader:
      template: |-
        go-pn532
        Copyright (c) {{ YEAR }} The Zaparoo Project Contributors.
        SPDX-License-Identifier: LGPL-3.0-or-later

        This file is part of go-pn532.

        go-pn532 is free software; you can redistribute it and/or
        modify it under the terms of the GNU Lesser General Public
        License as published by the Free Software Foundation; either
        version 3 of the License, or (at your option) any later version.

        go-pn532 is distributed in the hope that it will be useful,
        but WITHOUT ANY WARRANTY; without even the implied warranty of
        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
        Lesser General Public License for more details.

        You should have received a copy of the GNU Lesser General Public License
        along with go-pn532; if not, write to the Free Software Foundation,
        Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

formatters:
  enable:
    - gofumpt
    - gci
  